### ISSUE TITLE
过滤规则出错

### ISSUE THREAD

**Issue by KustuTear** [heinu123/ClashMeta_For_Magisk#2]
- 模块版本：clash for magisk-cloud-v29-beta1

- 问题：在blacklist模式下，开启模块后会过滤掉Google系app（自动代理Google系app已开）
表现也为Google apps和黑名单应用不走代理
其他软件正常代理

Dashboard内表现（部分）如下图
![Screenshot_2023-07-04-23-15-53-124_com.dashboard.kotlin-edit.jpg](https://github.com/heinu123/ClashMeta_For_Magisk/assets/93420845/3d193061-d886-43b4-832e-caad4a5e4227)

- 以下是相关的模块设置

packages.list（如图不包含任何Google apps）

![Screenshot_2023-07-04-23-09-56-003_bin.mt.plus-edit.jpg](https://github.com/heinu123/ClashMeta_For_Magisk/assets/93420845/5a300e90-0334-45b5-be82-2cd9384bf3a5)

clash.config

![Screenshot_2023-07-04-23-10-49-683_bin.mt.plus-edit.jpg](https://github.com/heinu123/ClashMeta_For_Magisk/assets/93420845/f3d3cb2c-ca50-452b-91e9-94d00c2ec599)

仅更换过频道里单独发布的最新的clash.iptables及clash.services

**Comment by elysias123** [comment]
这个是我忘记给黑名单模式添加额外判断了
毕竟黑名单模式也不需要勾选这个选项，忘记这茬了

**Comment by elysias123** [comment]
可以先关掉这个选项，v29beta2一会在tg频道发

**Comment by elysias123** [comment]
https://t.me/wtdnwbzda/882
