### ISSUE TITLE
29beta2

### ISSUE THREAD

**Issue by milo510334483** [heinu123/ClashMeta_For_Magisk#3]
刷入不会执行clashmeta的下载

**Comment by elysias123** [comment]
刷入模块并不会下载clashMeta
因为有些人下载实在是太太太太太太太慢了！会导致长时间卡在magisk安装页面，这样做会有个iss#4说安装magisk模块卡死了(
当你启动时会自动判断是否存在clashmeta内核，如果没有就会自动下载
